### ISSUE TITLE
Use a "solidity friendly" serialization format

### ISSUE THREAD

**Issue by heikoheiko** [brainbot-com/raiden#20]
The signed `MediatedTransfer` message and also `Locks` need to be deserializable in Solidity. 

see also: #21

**Comment by heikoheiko** [comment]
As there are no Solidity serialization libs, we need to revert to a simple handcrafted serialization. 

Proposal: use fixed-sized messages for signed data

**Comment by heikoheiko** [comment]
This also should be very fast.

**Comment by hackaugusto** [comment]
Fixed length format introduced with the commit: eed6e2d88d3caa755b2aa51d1ca5f8295b5ab670
