### ISSUE TITLE
Figure out how to handle deserialization in Solidity

### ISSUE THREAD

**Issue by czepluch** [brainbot-com/raiden#21]
Do Solidity libraries exist that can de/serialize messages (in eg. rlp or ABI encoding) sent to smart contracts?
If not, how can we solve this problem?

**Comment by czepluch** [comment]
According to Christian no such libraries libraries exist yet. He is however working on inline assembly and will rewrite the internal encoder / decoder in that language as a test of its usability. 

Either we should put efforts into creating such a library or use native contracts for MVP.

**Comment by heikoheiko** [comment]
#20
